### ISSUE TITLE
流局时不会重置押注，第六枪不开也算流局

### ISSUE THREAD

**Issue by sdyxxjj123** [Rs794613/PcrDuel#8]
改动了
    #结算下注金币，判定是否为超时局。
    if is_overtime == 1:
     if n !=6:
        msg = '本局为超时局，不进行金币结算，支持的金币全部返还。'
        await bot.send(ev, msg)
        duel_judger.set_support(ev.group_id)
        duel_judger.turn_off(ev.group_id)
        return
使得第六枪即便不开超时也不算是超时局，同时超时也会重置押注，之前没重置押注带来了一些不必要的麻烦

**Comment by Rs794613** [comment]
好的，我会加进去。
