### ISSUE TITLE
猜头像/猜角色

### ISSUE THREAD

**Issue by omoidesu** [Rs794613/PcrDuel#9]
__init__.py里的帮助有写
“一个女友只属于一位群友
  猜角色/猜头像获胜
  每日可获得6次100金币”

但是猜对也不会加金币，是不是没写相关功能？

**Comment by Rs794613** [comment]
这个是我自己魔改的 自己可以删掉这两句。

**Comment by omoidesu** [comment]
能不能给出魔改的代码参考一下？Orz

**Comment by Rs794613** [comment]
看着加金币那里改吧。
